spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234

#  data:
#    redis:
#      host: localhost
#      port: 6379

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    driver-class-name: com.mysql.cj.jdbc.Driver
#logging:
#  level:
#    com:
#      cqrs:
#        command : debug
#    org:
#      axonframework: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**

JWT:
  secret-key: wooyanofightingsecretjwtwooyanofightingsecretjwtbye
  expiration-time: 3600000
  refresh-expiration-time: 86400000
  header: Authorization
  prefix: Bearer

axon:
  axonserver:
    hostname: axon
    port: 8024
  serializer:
    general: xstream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}