spring:
  config:
    activate:
      on-profile: local

  datasource:
    url : jdbc:mysql://localhost:3306/reservation?serverTimezone=Asia/Seoul
    username: pjm
    password: jmjm1102
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  second-datasource:
  #    jdbcUrl : jdbc:mysql://localhost:3306/payment?serverTimezone=Asia/Seoul
  #    username: pjm
  #    password: jmjm1102
  #    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    topic: reservation-accept-events
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging.level:
  org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**

JWT:
  secret-key: wooyanofightingsecretjwtwooyanofightingsecretjwtbye
  expiration-time: 3600000
  refresh-expiration-time: 86400000
  header: Authorization
  prefix: Bearer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
axon:
  axonserver:
    servers: 127.0.0.1:8124
  serializer:
    general: xstream
  distributed:
    enabled: true





